export const inmemoryConfig = {
  PROTOKIT_BLOCK_INTERVAL: 5000,
  PROTOKIT_GRAPHQL_PORT: 8080,
  PROTOKIT_GRAPHQL_HOST: "localhost",
  PROTOKIT_GRAPHIQL_ENABLED: true,
};

export const developmentConfig = {
  PROTOKIT_PROOFS_ENABLED: false,
  PROTOKIT_SHOULD_ATTEMPT_DB_MIGRATION: true,
  PROTOKIT_SHOULD_ATTEMPT_INDEXER_DB_MIGRATION: true,
  PROTOKIT_SHOULD_ATTEMPT_PROCESSOR_DB_MIGRATION: true,
  PROTOKIT_PRUNE_ON_STARTUP: false,
  PROTOKIT_LOG_LEVEL: "INFO",

  PROTOKIT_BLOCK_INTERVAL: 30000,
  PROTOKIT_SETTLEMENT_INTERVAL: 60000,
  PROTOKIT_SETTLEMENT_ENABLED: true,

  REDIS_HOST: "localhost",
  REDIS_PORT: 6379,
  REDIS_PASSWORD: "password",

  DATABASE_URL:
    "postgresql://admin:password@localhost:5432/protokit?schema=public",

  INDEXER_DATABASE_URL:
    "postgresql://admin:password@localhost:5433/protokit-indexer?schema=public",

  PROCESSOR_DATABASE_URL:
    "postgresql://admin:password@localhost:5434/protokit-processor?schema=public",

  PROTOKIT_GRAPHQL_HOST: "0.0.0.0",
  PROTOKIT_GRAPHQL_PORT: 8080,
  PROTOKIT_GRAPHIQL_ENABLED: true,

  PROTOKIT_INDEXER_GRAPHQL_HOST: "0.0.0.0",
  PROTOKIT_INDEXER_GRAPHQL_PORT: 8081,
  PROTOKIT_INDEXER_GRAPHIQL_ENABLED: true,

  PROTOKIT_PROCESSOR_GRAPHQL_HOST: "0.0.0.0",
  PROTOKIT_PROCESSOR_GRAPHQL_PORT: 8082,
  PROTOKIT_PROCESSOR_GRAPHIQL_ENABLED: true,
  PROTOKIT_PROCESSOR_INDEXER_GRAPHQL_HOST: "0.0.0.0",

  MINA_NETWORK: "lightnet",
  MINA_NODE_GRAPHQL_HOST: "http://localhost",
  MINA_NODE_GRAPHQL_PORT: 8083,

  MINA_ARCHIVE_GRAPHQL_HOST: "http://localhost",
  MINA_ARCHIVE_GRAPHQL_PORT: 8085,

  MINA_ACCOUNT_MANAGER_HOST: "http://localhost",
  MINA_ACCOUNT_MANAGER_PORT: 8084,
  MINA_EXPLORER_PORT: 3001,

  PROTOKIT_TRANSACTION_FEE_RECIPIENT_PRIVATE_KEY:
    "EKEssvj33MMBCg2tcybTzL32nTKbbwFHm6yUxd3JassdhL3J5aT8",
  PROTOKIT_TRANSACTION_FEE_RECIPIENT_PUBLIC_KEY:
    "B62qk4sNnzZqqjHp8YQXZUV3dBpnjiNieJVnsuh7mD2bMJ9PdbskH5H",

  PROTOKIT_SEQUENCER_PRIVATE_KEY:
    "EKEdKhgUHMuDvwWJEg2TdCMCeiTSd9hh2HrEr6uYJfPVuwur1s43",
  PROTOKIT_SEQUENCER_PUBLIC_KEY:
    "B62qizW6aroTxQorJz4ywVNZom4jA6W4QPPCK3wLeyhnJHtVStUNniL",

  PROTOKIT_SETTLEMENT_CONTRACT_PRIVATE_KEY:
    "EKErS9gYHZNawqKuwfMiwYYJtNptCrvca491QEvB3tz8sFsS5w66",
  PROTOKIT_SETTLEMENT_CONTRACT_PUBLIC_KEY:
    "B62qjKhzrvDgTPXCp34ozmpFSx4sC9owZe6eDzhdGPdoiUbGPmBkHTt",

  PROTOKIT_DISPATCHER_CONTRACT_PRIVATE_KEY:
    "EKF9Ei5G9PeB5ULMh9R6P5LfWX2gs15XxPNsect1pbcbMY9vs6v7",
  PROTOKIT_DISPATCHER_CONTRACT_PUBLIC_KEY:
    "B62qmAzUJ1jqcsEf2V3K1k2Ec4MLsEKnodEvvJ5uweTFSLYEUALe1zs",

  PROTOKIT_MINA_BRIDGE_CONTRACT_PRIVATE_KEY:
    "EKFKTGqWU2egLKhMgoxX8mQ21zXSE1RZYkY82mmK9F3BxdSA7E5M",
  PROTOKIT_MINA_BRIDGE_CONTRACT_PUBLIC_KEY:
    "B62qn8XRkWcaBvv6F7kvarKs4cViaKRMbTUHT8FrDXLnvxuV6n7CHsN",

  PROTOKIT_CUSTOM_TOKEN_PRIVATE_KEY:
    "EKFZHQSo5YdrcU7neDaNZruYHvCiNncvdZyKXuS6MDCW1fyCFKDP",

  PROTOKIT_CUSTOM_TOKEN_ADMIN_PRIVATE_KEY:
    "EKENQ2QRc4gAJkZjQXU86ZS9MDm1e7HFiNN6LgRJnniHJt1WXDn1",

  PROTOKIT_CUSTOM_TOKEN_BRIDGE_PRIVATE_KEY:
    "EKENQ2QRc4gAJkZjQXU86ZS9MDm1e7HFiNN6LgRJnniHJt1WXDn1",

  TEST_ACCOUNT_1_PRIVATE_KEY:
    "EKF5p3wQTFd4tRBiGicRf93yXK82bcRryokC1qoazRM6wq6gMzWJ",
  TEST_ACCOUNT_1_PUBLIC_KEY:
    "B62qkVfEwyfkm5yucHEqrRjxbyx98pgdWz82pHv7LYq9Qigs812iWZ8",

  OPEN_TELEMETRY_TRACING_ENABLED: true,
  OPEN_TELEMETRY_TRACING_URL: "http://localhost:4318",

  OPEN_TELEMETRY_METRICS_ENABLED: true,
  OPEN_TELEMETRY_METRICS_HOST: "0.0.0.0",
  OPEN_TELEMETRY_METRICS_PORT: 4320,
  OPEN_TELEMETRY_METRICS_SCRAPING_FREQUENCY: 10,

};

export const sovereignConfig = {
  PROTOKIT_BLOCK_INTERVAL: 10000,
  PROTOKIT_SETTLEMENT_INTERVAL: 30000,
  PROTOKIT_SETTLEMENT_ENABLED: true,

  PROTOKIT_SHOULD_ATTEMPT_DB_MIGRATION: true,
  PROTOKIT_SHOULD_ATTEMPT_INDEXER_DB_MIGRATION: true,
  PROTOKIT_SHOULD_ATTEMPT_PROCESSOR_DB_MIGRATION: true,

  PROTOKIT_PRUNE_ON_STARTUP: false,
  PROTOKIT_LOG_LEVEL: "INFO",

  REDIS_HOST: "redis",
  REDIS_PORT: 6379,
  REDIS_PASSWORD: "password",

  DATABASE_URL:
    "postgresql://admin:password@postgres:5432/protokit?schema=public",

  INDEXER_DATABASE_URL:
    "postgresql://admin:password@indexer-postgres:5432/protokit-indexer?schema=public",

  PROCESSOR_DATABASE_URL:
    "postgresql://admin:password@processor-postgres:5432/protokit-processor?schema=public",

  PROTOKIT_GRAPHQL_HOST: "0.0.0.0",
  PROTOKIT_GRAPHQL_PORT: 8080,
  PROTOKIT_GRAPHIQL_ENABLED: true,

  PROTOKIT_INDEXER_GRAPHQL_HOST: "0.0.0.0",
  PROTOKIT_INDEXER_GRAPHQL_PORT: 8081,
  PROTOKIT_INDEXER_GRAPHIQL_ENABLED: true,

  PROTOKIT_PROCESSOR_GRAPHQL_HOST: "0.0.0.0",
  PROTOKIT_PROCESSOR_GRAPHQL_PORT: 8082,
  PROTOKIT_PROCESSOR_GRAPHIQL_ENABLED: true,
  PROTOKIT_PROCESSOR_INDEXER_GRAPHQL_HOST: "indexer",

  MINA_NETWORK: "lightnet",
  MINA_NODE_GRAPHQL_HOST: "http://lightnet",
  MINA_NODE_GRAPHQL_PORT: 8080,

  MINA_ARCHIVE_GRAPHQL_HOST: "http://lightnet",
  MINA_ARCHIVE_GRAPHQL_PORT: 8282,

  MINA_ACCOUNT_MANAGER_HOST: "http://lightnet",
  MINA_ACCOUNT_MANAGER_PORT: 8084,
  MINA_EXPLORER_PORT: 3001,

  PROTOKIT_TRANSACTION_FEE_RECIPIENT_PRIVATE_KEY:
    "EKEssvj33MMBCg2tcybTzL32nTKbbwFHm6yUxd3JassdhL3J5aT8",
  PROTOKIT_TRANSACTION_FEE_RECIPIENT_PUBLIC_KEY:
    "B62qk4sNnzZqqjHp8YQXZUV3dBpnjiNieJVnsuh7mD2bMJ9PdbskH5H",

  PROTOKIT_SEQUENCER_PRIVATE_KEY:
    "EKEdKhgUHMuDvwWJEg2TdCMCeiTSd9hh2HrEr6uYJfPVuwur1s43",
  PROTOKIT_SEQUENCER_PUBLIC_KEY:
    "B62qizW6aroTxQorJz4ywVNZom4jA6W4QPPCK3wLeyhnJHtVStUNniL",

  PROTOKIT_SETTLEMENT_CONTRACT_PRIVATE_KEY:
    "EKErS9gYHZNawqKuwfMiwYYJtNptCrvca491QEvB3tz8sFsS5w66",
  PROTOKIT_SETTLEMENT_CONTRACT_PUBLIC_KEY:
    "B62qjKhzrvDgTPXCp34ozmpFSx4sC9owZe6eDzhdGPdoiUbGPmBkHTt",

  PROTOKIT_DISPATCHER_CONTRACT_PRIVATE_KEY:
    "EKF9Ei5G9PeB5ULMh9R6P5LfWX2gs15XxPNsect1pbcbMY9vs6v7",
  PROTOKIT_DISPATCHER_CONTRACT_PUBLIC_KEY:
    "B62qmAzUJ1jqcsEf2V3K1k2Ec4MLsEKnodEvvJ5uweTFSLYEUALe1zs",

  PROTOKIT_MINA_BRIDGE_CONTRACT_PRIVATE_KEY:
    "EKFKTGqWU2egLKhMgoxX8mQ21zXSE1RZYkY82mmK9F3BxdSA7E5M",
  PROTOKIT_MINA_BRIDGE_CONTRACT_PUBLIC_KEY:
    "B62qn8XRkWcaBvv6F7kvarKs4cViaKRMbTUHT8FrDXLnvxuV6n7CHsN",

  TEST_ACCOUNT_1_PRIVATE_KEY:
    "EKF5p3wQTFd4tRBiGicRf93yXK82bcRryokC1qoazRM6wq6gMzWJ",
  TEST_ACCOUNT_1_PUBLIC_KEY:
    "B62qkVfEwyfkm5yucHEqrRjxbyx98pgdWz82pHv7LYq9Qigs812iWZ8",
  
  OPEN_TELEMETRY_TRACING_ENABLED: true,
  OPEN_TELEMETRY_TRACING_URL: "http://otel-collector:4317",

  OPEN_TELEMETRY_METRICS_ENABLED: true,
  OPEN_TELEMETRY_METRICS_HOST: "0.0.0.0",
  OPEN_TELEMETRY_METRICS_PORT: 4320,
  OPEN_TELEMETRY_METRICS_SCRAPING_FREQUENCY: 10,

};