name: Release NPM Packages

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Current git sha for the website to pull from'
        required: true
  push:
    branches:
      - develop
  
permissions:
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22.9.0
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - name: "Install dependencies"
        run: npm ci --workspaces --include-workspace-root

      - name: "Build"
        run: npm run build

      - name: Run Lerna Release
        run: npm run publish:canary

      - name: Trigger website build & deployment
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
        run: |
          curl -X POST -d {} $NETLIFY_BUILD_HOOK
